"use strict";
// This file is auto-generated by TanStack Router
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
const react_router_1 = require("@tanstack/react-router");
// Import Routes
const __root_1 = require("./routes/__root");
// Create Virtual Routes
const RoomLazyImport = (0, react_router_1.createFileRoute)('/room')();
const IndexLazyImport = (0, react_router_1.createFileRoute)('/')();
// Create/Update Routes
const RoomLazyRoute = RoomLazyImport.update({
    path: '/room',
    getParentRoute: () => __root_1.Route,
}).lazy(() => import('./routes/room.lazy').then((d) => d.Route));
const IndexLazyRoute = IndexLazyImport.update({
    path: '/',
    getParentRoute: () => __root_1.Route,
}).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
// Create and export the route tree
exports.routeTree = __root_1.Route.addChildren([IndexLazyRoute, RoomLazyRoute]);
